<Project Sdk="Microsoft.NET.Sdk">

	<ItemGroup>
		<ProjectReference Include="..\WaylaAI.Booking.Application\WaylaAI.Booking.Application.csproj" />
		<ProjectReference Include="..\WaylaAI.Booking.Domain\WaylaAI.Booking.Domain.csproj" />
	</ItemGroup>

	<ItemGroup>
		<PackageReference Include="Auth0.AuthenticationApi" Version="7.47.0" />
		<PackageReference Include="Microsoft.AspNetCore.HeaderPropagation" Version="10.0.10" />
		<PackageReference Include="Microsoft.EntityFrameworkCore" Version="10.0.10" />
		<PackageReference Include="Microsoft.EntityFrameworkCore.InMemory" Version="10.0.10" />
		<PackageReference Include="Npgsql.EntityFrameworkCore.PostgreSQL" Version="10.0.3" />
		<PackageReference Include="Refit" Version="13.1.0" />
		<PackageReference Include="Refit.HttpClientFactory" Version="13.1.0" />
	</ItemGroup>

	<ItemGroup>
		<FrameworkReference Include="Microsoft.AspNetCore.App" />
	</ItemGroup>

	<PropertyGroup>
		<TargetFramework>net10.0</TargetFramework>
		<ImplicitUsings>enable</ImplicitUsings>
		<Nullable>enable</Nullable>
	</PropertyGroup>

</Project>
