// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using WaylaAI.Booking.Infrastructure.Database;

#nullable disable

namespace WaylaAI.Booking.Infrastructure.Migrations
{
    [DbContext(typeof(BookingDbContext))]
    partial class BookingDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("WaylaAI.Booking.Domain.Entities.Booking", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("Date")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Destination")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.HasKey("Id");

                    b.ToTable("Bookings");

                    b.HasData(
                        new
                        {
                            Id = new Guid("d343467c-d6b3-4f9e-a868-233bb93efd68"),
                            Date = new DateTime(2027, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Destination = "Paris",
                            Price = 1250.00m,
                            UserId = "auth0|mocked-user-id"
                        },
                        new
                        {
                            Id = new Guid("b11c97f1-7c96-48cf-94f7-e435967bb1d9"),
                            Date = new DateTime(2027, 3, 15, 0, 0, 0, 0, DateTimeKind.Utc),
                            Destination = "Tokyo",
                            Price = 2800.00m,
                            UserId = "auth0|mocked-user-id"
                        },
                        new
                        {
                            Id = new Guid("6789f2a9-c89b-466d-8c43-f6d8961726a7"),
                            Date = new DateTime(2027, 5, 20, 0, 0, 0, 0, DateTimeKind.Utc),
                            Destination = "New York",
                            Price = 900.50m,
                            UserId = "auth0|mocked-user-id"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
